import { LyricLine, LrcMetadata } from './lyric-utils';

export interface AssOptions {
  primaryColor: string; // hex
  color2: string; // hex
  color3: string; // hex
  chorusColor: string; // hex
  fontFamily: string;
  fontSize: number;
  songInfoTitle: string;
  songInfoArtist: string;
  songInfoAlbum: string;
  songInfoCustom: string;
  customStartInfoTime: boolean;
  startInfoStartTime: number;
  startInfoEndTime: number;
  interludeThreshold: number; // in seconds
  fadeInOutTime: number; // in seconds
}

// 內部控制參數定
const INTERNAL_NEXT_TRIGGER_INDEX = 1; // 唱到下一句的第 2 個字時 (index = 1) 切換
// 'immediate': 該句自己唱完結尾立刻從畫面消失切換
// 'delayed': 等待下一行（第一排）開始唱且唱到第 2 個字時才從畫面上消失並替換
const INTERNAL_ROW2_FADEOUT_MODE: 'immediate' | 'delayed' = 'immediate';

function formatAssTime(timeInSeconds: number) {
  const h = Math.floor(timeInSeconds / 3600);
  const m = Math.floor((timeInSeconds % 3600) / 60);
  const s = Math.floor(timeInSeconds % 60);
  const cs = Math.floor((timeInSeconds % 1) * 100);
  return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${cs.toString().padStart(2, '0')}`;
}

function hexToAssColor(hex: string) {
  let cleanHex = hex.replace('#', '');
  if (cleanHex.length === 6) {
    const r = cleanHex.slice(0, 2);
    const g = cleanHex.slice(2, 4);
    const b = cleanHex.slice(4, 6);
    return `&H00${b}${g}${r}`;
  }
  return `&H00FFFFFF`;
}

// 產生 SVG 風格的小白圓向量圖形 (ASS Vector)
function getDotsVector(count: number, r: number, spacing: number) {
   let path = '';
   for (let i = 0; i < count; i++) {
      const cx = i * spacing;
      // 貝茲曲線控制點用來畫圓 (圓半徑 * 0.55228)
      const c = Math.round(r * 0.55228);
      path += `m ${cx} ${-r} b ${cx+c} ${-r} ${cx+r} ${-c} ${cx+r} 0 b ${cx+r} ${c} ${cx+c} ${r} ${cx} ${r} b ${cx-c} ${r} ${cx-r} ${c} ${cx-r} 0 b ${cx-r} ${-c} ${cx-c} ${-r} ${cx} ${-r} `;
   }
   return path;
}

function getLineEndTime(line: LyricLine): number {
    if (line.end !== null) return line.end;
    if (line.words && line.words.length > 0) {
        const lastWord = line.words[line.words.length - 1];
        if (lastWord.start !== null) {
            if (lastWord.text.trim() === '') {
                return lastWord.start;
            }
            return lastWord.start + Math.max(0.5, lastWord.text.length * 0.2);
        }
    }
    return (line.start || 0) + 2;
}

export function generateAss(lines: LyricLine[], metadata: LrcMetadata, options: AssOptions): string {
  const primaryAssColor = hexToAssColor(options.primaryColor);
  
  // 樣式設定
  const styles = `[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${options.fontFamily},20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: TopLeft,${options.fontFamily},72,&H00FFFFFF,&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,3,1.5,0,7,48,48,48,0
Style: TopCenter,${options.fontFamily},72,&H00FFFFFF,&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,3,1.5,0,8,48,48,48,0
Style: TopRight,${options.fontFamily},72,&H00FFFFFF,&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,3,1.5,0,9,48,48,48,0
Style: BottomLeft,${options.fontFamily},${options.fontSize},${primaryAssColor},&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,1,4,0,1,150,150,250,0
Style: BottomCenter,${options.fontFamily},${options.fontSize},${primaryAssColor},&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,1,4,0,2,48,48,48,0
Style: BottomRight,${options.fontFamily},${options.fontSize},${primaryAssColor},&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,1,4,0,3,150,150,50,0
Style: CenterInfo,${options.fontFamily},${options.fontSize},${primaryAssColor},&H00FFFFFF,&H99000000,&H99000000,0,0,0,0,100,100,0,0,1,4,0,5,48,48,48,0
`;

  let ass = `[Script Info]
; Script generated by Enhanced LRC Studio KTV Exporter
Title: KTV ASS
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

${styles}
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  // 過濾掉無效的歌詞行
  const validLines = lines.filter(l => l.start !== null && l.words.some(w => w.text.trim().length > 0));
  
  // 依據「間奏閥值」(interludeThreshold) 將歌詞切分成段落
  const paragraphs: LyricLine[][] = [];
  let currentPara: LyricLine[] = [];
  
  for (let i = 0; i < validLines.length; i++) {
    const line = validLines[i];
    const prevEnd = i > 0 ? getLineEndTime(validLines[i - 1]) : 0;
    
    if (currentPara.length > 0 && line.start! - prevEnd >= options.interludeThreshold) {
      paragraphs.push(currentPara);
      currentPara = [];
    }
    currentPara.push(line);
  }
  if (currentPara.length > 0) paragraphs.push(currentPara);
  
  // 歌曲前奏資訊計算
  let infoStart = 0;
  let infoEnd = 6;
  if (!options.customStartInfoTime) {
    if (paragraphs.length > 0 && paragraphs[0][0].start! < 6) {
       const firstParaEnd = getLineEndTime(paragraphs[0][paragraphs[0].length - 1]);
       if (firstParaEnd > 60) {
           infoStart = 0;
           infoEnd = 6;
       } else {
           infoStart = firstParaEnd;
           infoEnd = firstParaEnd + 6;
       }
    } else {
       infoStart = 0;
       infoEnd = Math.min(6, paragraphs.length > 0 ? paragraphs[0][0].start! : 6);
    }
  } else {
    infoStart = options.startInfoStartTime;
    infoEnd = options.startInfoEndTime;
  }
  
  const fadeMs = Math.round(options.fadeInOutTime * 1000);

  // 組織歌曲標題與歌手資訊，並放入畫面正中央
  let infoText = '';
  if (options.songInfoTitle) {
      // 標題字體不加白底外框，僅使用紅色顏色
      infoText += `{\\c&H000000FF&\\b1}${options.songInfoTitle}{\\b0}`;
      if (options.songInfoArtist || options.songInfoAlbum || options.songInfoCustom) {
         // 標題與藍色資訊間隔 3 行 (相當於 4 個換行符號)
         infoText += '\\N\\N\\N\\N';
      }
  }
  const artistAlbum = [];
  if (options.songInfoArtist) artistAlbum.push(`{\\c&H00FF0000&}原唱：${options.songInfoArtist}`);
  if (options.songInfoAlbum) artistAlbum.push(`{\\c&H00FF0000&}專輯：${options.songInfoAlbum}`);
  if (options.songInfoCustom) artistAlbum.push(`{\\c&H00FF0000&}${options.songInfoCustom}`);
  infoText += artistAlbum.join('\\N');

  if (infoText) {
      // 使用 CenterInfo 樣式（ Alignment 5 ）放中央
      ass += `Dialogue: 10,${formatAssTime(infoStart)},${formatAssTime(infoEnd)},CenterInfo,,0,0,0,,{\\fad(${fadeMs},${fadeMs})\\pos(960,540)}${infoText}\n`;
  }

  // 倒數小白圓的控制參數
  const dotDuration = 1.0;
  // 計算小白圓與文字的相對大小，並使其「稍大一點點」
  const dotRadius = Math.round(options.fontSize * 0.3); 
  const dotSpacing = Math.round(options.fontSize * 0.8);
  
  paragraphs.forEach((p, idx) => {
      const prevEnd = idx > 0 ? getLineEndTime(paragraphs[idx - 1][paragraphs[idx - 1].length - 1]) : 0;
      const gap = p[0].start! - prevEnd;
      
      let dotCount = 0;
      // 保留最後 1 秒鐘為「沒有小白圓」的留白階段
      const availDotsTime = gap - 1.0; 
      let maxAdvance = p[0].start!; // 首段的話，可利用的時間是 0 到 start
      if (idx > 0) maxAdvance = gap;

      if (maxAdvance > 1.0) {
          // 最多顯示 4 個倒數小圓
          dotCount = Math.min(4, Math.floor(maxAdvance - 1.0));
      }
      
      let actualAdvance = 0;
      if (dotCount > 0) {
         // 若有倒數小白圓，歌詞提早顯示時間配合圓點
         actualAdvance = dotCount * dotDuration + 1.0 + options.fadeInOutTime;
      } else {
         actualAdvance = Math.min(2.0, maxAdvance) + options.fadeInOutTime;
      }
      
      // 計算段落顯示總體時間
      const blockDisplayStart = Math.max(prevEnd, p[0].start! - actualAdvance);
      // 間奏前多留 1 秒（原為 + 1.0 變成 + 2.0），讓句子不要太快消失
      const blockDisplayEnd = getLineEndTime(p[p.length - 1]) + 2.0 + options.fadeInOutTime; 
      const truncatedBlockEnd = idx < paragraphs.length - 1 ? Math.min(blockDisplayEnd, paragraphs[idx + 1][0].start! - 0.1) : blockDisplayEnd;

      // 產生倒數小白圓的 Events
      if (dotCount > 0) {
          const isSingleLine = p.length === 1;
          
          let xPos = 0;
          let yPos = 0;
          // 計算第一行文字上方的適當座標位置
          if (isSingleLine) {
             const totalW = (dotCount - 1) * dotSpacing + 2 * dotRadius;
             // BottomCenter 座標
             xPos = 960 - (totalW / 2) + dotRadius; 
             yPos = 1080 - 48 - options.fontSize - dotRadius - 20;
          } else {
             // BottomLeft 座標
             xPos = 150 + dotRadius;
             yPos = 1080 - 250 - options.fontSize - dotRadius - 20;
          }

          for (let d = 0; d < dotCount; d++) {
             const dDots = dotCount - d;
             // 第一個圓出現的時間
             let dotStart = p[0].start! - 1.0 - dDots;
             let dotEnd = dotStart + dotDuration;
             
             let dotFadeIn = 0;
             if (d === 0) {
                 dotStart -= options.fadeInOutTime;
                 dotFadeIn = fadeMs;
             }
             
             const vecStr = getDotsVector(dDots, dotRadius, dotSpacing);
             // {\\p1} 使用 SVG Vector 畫法, {\\c...\\3c...} 指定填滿與邊框色彩
             ass += `Dialogue: 5,${formatAssTime(dotStart)},${formatAssTime(dotEnd)},TopLeft,,0,0,0,,{\\fad(${dotFadeIn},0)\\pos(${xPos},${yPos})\\c&HFFFFFF&\\bord0\\shad0\\1a&H00&}{\\p1}${vecStr}{\\p0}\n`;
          }
      }

      // 針對段落內的每行歌詞進行處理
      for (let i = 0; i < p.length; i++) {
         const line = p[i];
         // 判斷該段落最後一句是否為奇數行置中
         const lastIsCentered = p.length % 2 !== 0 && p.length >= 3;
         const isLast = i === p.length - 1;
         const isCentered = isLast && lastIsCentered;

         const isSingleLine = p.length === 1;
         const isReallyCentered = isCentered || isSingleLine;

         // 決定雙行樣式
         const row = isReallyCentered ? 2 : ((i % 2 === 0) ? 1 : 2);
         const style = isReallyCentered ? 'BottomCenter' : (row === 1 ? 'BottomLeft' : 'BottomRight');

         let displayStart = blockDisplayStart;
         if (isCentered) {
            // 如果是最後一句置中的，等前一句唱完才出現
            const prevLine = p[i - 1];
            displayStart = getLineEndTime(prevLine);
         } else if (i >= 2) {
            if (i % 2 === 0) {
               // 第一排 (偶數句) 換場：等下一句 (前排, 即 i-1) 唱到第2個字時切換
               const prevLine = p[i - 1];
               const trigIdx = Math.min(INTERNAL_NEXT_TRIGGER_INDEX, prevLine.words.length - 1);
               const trigWord = prevLine.words[trigIdx];
               displayStart = (trigWord && trigWord.start !== null) ? trigWord.start : getLineEndTime(prevLine);
            } else {
               // 第二排 (奇數句) 換場：等自己上一句同排的字 (即 i-2) 唱完後立刻切換
               const prevSameRowLine = p[i - 2];
               displayStart = getLineEndTime(prevSameRowLine);
            }
         }

         let displayEnd = truncatedBlockEnd;
         
         if (isReallyCentered) {
            // 最後一句置中的句，一直留到段落結束
            displayEnd = truncatedBlockEnd;
         } else if (lastIsCentered && i >= p.length - 3 && i !== p.length - 1) {
            // 如果接下來有最後一句置中的情況：
            // p.length - 2 (也就是第二句，row 2) 以及 p.length - 3 (第一句，row 1)
            // 這兩句都應該在「最後置中句」出現時消失！也就是前一句唱完時結束
            const prevLineToTarget = p[p.length - 2];
            displayEnd = getLineEndTime(prevLineToTarget);
         } else if (i < p.length - 2) {
            if (i % 2 === 0) {
               // 第一排 (偶數句) 消失：等「下一句」唱到第2個字時被切掉
               const nextLine = p[i + 1];
               const trigIdx = Math.min(INTERNAL_NEXT_TRIGGER_INDEX, nextLine.words.length - 1);
               const trigWord = nextLine.words[trigIdx];
               const trigTime = (trigWord && trigWord.start !== null) ? trigWord.start : getLineEndTime(nextLine);
               displayEnd = trigTime;
            } else {
               if (INTERNAL_ROW2_FADEOUT_MODE === 'delayed') {
                   // 第二排 (奇數句) 消失：等下一句 (第一排) 唱到第2個字時才消失
                   const nextLine = p[i + 1];
                   const trigIdx = Math.min(INTERNAL_NEXT_TRIGGER_INDEX, nextLine.words.length - 1);
                   const trigWord = nextLine.words[trigIdx];
                   const trigTime = (trigWord && trigWord.start !== null) ? trigWord.start : getLineEndTime(nextLine);
                   displayEnd = trigTime;
               } else {
                   // 第二排 (奇數句) 消失：自己唱完後立刻消失被切走
                   const currLine = p[i];
                   displayEnd = getLineEndTime(currLine);
               }
            }
         }
         
         if (displayEnd <= displayStart) {
            displayEnd = displayStart + 1;
         }

         // 前兩行套用淡入，最後段落結尾套用淡出
         let fadeIn = (i === 0 || i === 1) ? fadeMs : 0;
         let fadeOut = 0;
         if (lastIsCentered && i === p.length - 1) {
             fadeOut = fadeMs;
         } else if (!lastIsCentered && (i === p.length - 1 || i === p.length - 2)) {
             fadeOut = fadeMs;
         } else if (isSingleLine) {
             fadeOut = fadeMs;
         }

         let karaokeStr = '';
         const validWords = line.words.filter(w => w.text.trim().length > 0 || w.text === ' ');
         for (let wIdx = 0; wIdx < validWords.length; wIdx++) {
            const w = validWords[wIdx];
            
            let durCs = 0;
            if (w.start !== null) {
               const nextW = validWords[wIdx + 1];
               const nextStart = nextW ? nextW.start : line.end;
               if (nextStart !== null && nextStart > w.start) {
                   durCs = Math.round((nextStart - w.start) * 100);
               } else {
                   durCs = 30; // 預設 300ms 保護機制
               }
            } else {
               durCs = 30;
            }
            if (!w.text.trim()) {
               karaokeStr += `{\\k${durCs}}${w.text}`; 
            } else {
               karaokeStr += `{\\kf${durCs}}${w.text}`;
            }
         }

         // 句首空白等待，確保 KTV 變色的精準性
         const startDelaySec = (line.start || displayStart) - displayStart;
         if (startDelaySec > 0) {
            karaokeStr = `{\\kf${Math.round(startDelaySec * 100)}}${karaokeStr}`;
         }

         ass += `Dialogue: ${row},${formatAssTime(displayStart)},${formatAssTime(displayEnd)},${style},,0,0,0,,{\\fad(${fadeIn},${fadeOut})}${karaokeStr}\n`;
      }
  });

  return ass;
}

